/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaymentRequest {
  export type PaymentRequestDataStruct = {
    merchant: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    status: BigNumberish;
    payer: AddressLike;
    paidAt: BigNumberish;
  };

  export type PaymentRequestDataStructOutput = [
    merchant: string,
    token: string,
    amount: bigint,
    timestamp: bigint,
    status: bigint,
    payer: string,
    paidAt: bigint
  ] & {
    merchant: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
    status: bigint;
    payer: string;
    paidAt: bigint;
  };
}

export interface PaymentRequestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC_POLYGON"
      | "USDT_POLYGON"
      | "cancelPaymentRequest"
      | "createPaymentRequest"
      | "getCurrentPaymentId"
      | "getPaymentRequest"
      | "getSupportedTokens"
      | "markAsPaid"
      | "nextPaymentId"
      | "owner"
      | "paymentExists"
      | "paymentRequests"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentCancelled"
      | "PaymentFulfilled"
      | "PaymentRequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "USDC_POLYGON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_POLYGON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPaymentRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPaymentRequest",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markAsPaid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "USDC_POLYGON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_POLYGON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCancelledEvent {
  export type InputTuple = [paymentId: BigNumberish, cancelledAt: BigNumberish];
  export type OutputTuple = [paymentId: bigint, cancelledAt: bigint];
  export interface OutputObject {
    paymentId: bigint;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFulfilledEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    payer: AddressLike,
    paidAt: BigNumberish
  ];
  export type OutputTuple = [paymentId: bigint, payer: string, paidAt: bigint];
  export interface OutputObject {
    paymentId: bigint;
    payer: string;
    paidAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRequestCreatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    merchant: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    merchant: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    merchant: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRequest extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRequest;
  waitForDeployment(): Promise<this>;

  interface: PaymentRequestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC_POLYGON: TypedContractMethod<[], [string], "view">;

  USDT_POLYGON: TypedContractMethod<[], [string], "view">;

  cancelPaymentRequest: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPaymentRequest: TypedContractMethod<
    [merchant: AddressLike, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getCurrentPaymentId: TypedContractMethod<[], [bigint], "view">;

  getPaymentRequest: TypedContractMethod<
    [paymentId: BigNumberish],
    [PaymentRequest.PaymentRequestDataStructOutput],
    "view"
  >;

  getSupportedTokens: TypedContractMethod<
    [],
    [[string, string] & { usdc: string; usdt: string }],
    "view"
  >;

  markAsPaid: TypedContractMethod<
    [paymentId: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentExists: TypedContractMethod<
    [paymentId: BigNumberish],
    [boolean],
    "view"
  >;

  paymentRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, bigint] & {
        merchant: string;
        token: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
        payer: string;
        paidAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC_POLYGON"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT_POLYGON"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelPaymentRequest"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPaymentRequest"
  ): TypedContractMethod<
    [merchant: AddressLike, token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaymentRequest"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [PaymentRequest.PaymentRequestDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<
    [],
    [[string, string] & { usdc: string; usdt: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsPaid"
  ): TypedContractMethod<
    [paymentId: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentExists"
  ): TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, bigint] & {
        merchant: string;
        token: string;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
        payer: string;
        paidAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCancelled"
  ): TypedContractEvent<
    PaymentCancelledEvent.InputTuple,
    PaymentCancelledEvent.OutputTuple,
    PaymentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFulfilled"
  ): TypedContractEvent<
    PaymentFulfilledEvent.InputTuple,
    PaymentFulfilledEvent.OutputTuple,
    PaymentFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRequestCreated"
  ): TypedContractEvent<
    PaymentRequestCreatedEvent.InputTuple,
    PaymentRequestCreatedEvent.OutputTuple,
    PaymentRequestCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentCancelled(uint256,uint256)": TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;
    PaymentCancelled: TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;

    "PaymentFulfilled(uint256,address,uint256)": TypedContractEvent<
      PaymentFulfilledEvent.InputTuple,
      PaymentFulfilledEvent.OutputTuple,
      PaymentFulfilledEvent.OutputObject
    >;
    PaymentFulfilled: TypedContractEvent<
      PaymentFulfilledEvent.InputTuple,
      PaymentFulfilledEvent.OutputTuple,
      PaymentFulfilledEvent.OutputObject
    >;

    "PaymentRequestCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PaymentRequestCreatedEvent.InputTuple,
      PaymentRequestCreatedEvent.OutputTuple,
      PaymentRequestCreatedEvent.OutputObject
    >;
    PaymentRequestCreated: TypedContractEvent<
      PaymentRequestCreatedEvent.InputTuple,
      PaymentRequestCreatedEvent.OutputTuple,
      PaymentRequestCreatedEvent.OutputObject
    >;
  };
}
